SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `idbooks` INT NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `review` VARCHAR(100) NOT NULL,
  `authors` VARCHAR(150) NOT NULL,
  `categories` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  `publisher` VARCHAR(75) NOT NULL,
  `thumb` VARCHAR(100) NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idbooks`),
  INDEX `fk_books_users_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_books_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;